### ISSUE TITLE
How to remove animation for selected item?

### ISSUE THREAD

**Issue by IArjunChudasa** [v-braun/VBRRollingPit#17]
first, thank you for such a great library.
i don't to show selected item. how to remove animation from every where 
I set 0 for circle radius but its now working. please help me.

**Comment by v-braun** [comment]
what is your expected behavior? which animation do you want to remove?
it makes no sense to "not show the selected item" with this control because the circle shows always the current selected one. 

do you want that the cirlce stays always on the first entry even when the user selects the 2nd or third one??
